#!/bin/sh

# Name   : Docker Installer
# Author : W.S.Kaushalya
# Contributers : Sehan Weerasekara (S3H4N)
# Date   : 01/19/2022
# Description : This will install Docker engine in any Ubuntu based desktop.

# Print banner
tput bold && tput rev
echo ""
echo " Docker-Installer v 1.1 "
echo ""
tput sgr0

# Uninstall old versions
sudo apt-get remove docker docker-engine docker.io containerd runc

# Update the system and setup Docker repo
sudo apt-get update
sudo apt-get install \
  ca-certificates \
  curl \
  gnupg \
  lsb-release

# Add Docker's official GPG key
curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg -y

# Setup Docker's stable repository
echo \
  "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu \
  $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list >/dev/null

# Install Docker engine
sudo apt-get update
sudo apt-get install docker-ce docker-ce-cli containerd.io -y

# Setup user permissions
sudo groupadd docker          # create docker group
sudo usermod -aG docker $USER # add user to docker group

# Fix ownership
sudo chown "$USER":"$USER" /home/"$USER"/.docker -R
sudo chmod g+rwx "$HOME/.docker" -R

# Configure to start on boot
sudo systemctl enable docker.service
sudo systemctl enable containerd.service

# Install Docker-Compose v 1.29.2
sudo curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
sudo chmod +x /usr/local/bin/docker-compose # setup permissions
docker-compose --version

# Setup user permission of Docker.socket
sudo chmod 666 /var/run/docker.sock
